### ISSUE TITLE
Add Error messages to sign up page

### ISSUE THREAD

**Issue by kesdlvi** [tr-vs/realist#7]
Currently our sign up page will add a user to the database, but only if all input fields are filled in correctly. 

Since we are all human, there are bound to some errors for new users (using a taken username, bad password, invalid email, etc) 

We will need to display these errors on the sign up page. It should prevent a user submission to the database and instead display a message which echos what the issue is. 

There is plenty of white space to display this message, if anything we can move the sign up box to the side. We also could make a popup to display the error. We will discuss this. 

<img width="1512" alt="Screenshot 2023-11-02 at 10 28 16 PM" src="https://github.com/tr-vs/realist/assets/85363542/9460310b-6687-4539-85de-f231f3988dca">

**Comment by sau-sal** [comment]
I would like to work on this. Please assign it to me.

**Comment by kesdlvi** [comment]
> I would like to work on this. Please assign it to me.

Send a pull req

**Comment by sau-sal** [comment]
I m getting this IP whitelisting error while running backend app -

MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
