### ISSUE TITLE
Landing page button style fix

### ISSUE THREAD

**Issue by kesdlvi** [tr-vs/realist#89]
On our landing page the button that hovers at the bottom of the screen has some sizing issues. Depending on the window size the text within the button stacks on itself. We want, for the most part, for the text to remain on one line. 

**Possible ways to fix**
Looking at the code we either can:

- Fix the text size
or

- Fix how the button sizing works. 

The job is to figure out which solution is best. 

![Uploading Screenshot 2023-11-26 at 9.22.47 PM.png…]()

**Comment by ishanaudichya** [comment]
Hey I have fixed this issue, please check and merge if possible. 
Thanks
